app.config.webServiceUrl=http://localhost:3310/
app.config.webServiceAPIKey=lBxskXzo_fXsCC9WkcPscuymGDkiy1DgMrBidEeFZjIpvmRFOwHXaEgH7cJmgiAhMZxFHht6d
app.config.appFolderPath=/Users/edemmawut/Documents/Projects/uploads/DMSS/

server.error.whitelabel.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration

AES_ALGORITHM=AES
AES_TRANSFORMATION=AES/ECB/PKCS5Padding
AES_SECRET_KEY=f1504676778717f339fe1a25acc8d4b6

# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=
# spring.mail.password=
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# EUDR API Configuration
# Google Maps API key
# google.maps.api.key=

# Rate limiting for FREE APIs
api.rate.limit.google-maps=28000
api.rate.limit.nominatim=1
api.rate.limit.overpass=1